# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jF-XOPKLlN8aoJD02VtSQIwsAGMbrIuN
"""

# 1.
n = int(input("Masukkan nilai: "))
segitiga = []
for i in range(n):
    baris = [1]
    for j in range(1, i):
      baris.append(segitiga[i-1][j-1] + segitiga[i-1][j])
    if i : baris.append(1)
    segitiga.append(baris)


lebar = len(' '.join(map(str, segitiga[-1])))
for baris in segitiga:
    print(' '.join(map(str, baris)).center(lebar))

#2
def jumlah_bilangan_prima(m):
  def prima(x) :
    if x < 2: return False
    for i in range(2, int(x**0.5) + 1):
        if x % i == 0:
          return False
    return True
  return sum(i for i in range(1, m + 1) if prima(i))

n = int(input("Masukkan Angka : "))
print(jumlah_bilangan_prima(n))

#3
data = [
    "Seth Morrison",
    "Ben Kasica",
    "John Cooper",
    "Jen Ledger",
]

def sort_nama(nama):
  return sorted(nama, key=lambda x: x.split()[-1])

hasil = sort_nama(data)
for nm in hasil:
  print(nm)

#4
def terbilang(n):
  satuan = ["","satu","dua","tiga","empat","lima","enam","tujuh","delapan","sembilan"]

  if n == 0:
    return "nol"
  elif n < 10:
    return satuan[n]
  elif n == 10:
    return "sepuluh "
  elif n == 11:
    return "sebelas"
  elif n < 20:
    return satuan[n % 10] + " belas"
  elif n < 100:
    return satuan[n//10] + " puluh" + (" " + terbilang(n%10) if n%10 else "")
  elif n < 200:
    return "seratus" + (" " + terbilang(n%100) if n%100 != 0 else "")
  elif n < 1000:
    return satuan[n//100] + " ratus" + (" " + terbilang(n%100) if n%100 != 0 else "")
  elif n < 2000:
    return "seribu" + (" " + terbilang(n%1000) if n%1000 != 0 else "")
  elif n <= 9999:
    return terbilang(n//1000) + " ribu" + (" " + terbilang(n%1000) if n%1000 != 0 else "")
  else:
    return "Angka terlalu besar"

n = int(input("Masukkan Angka : "))
print(terbilang(n))

#5
n = int(input("Masukkan Angka : "))
binary = bin(n)[2:]
print(binary)

#6
def cek_palindrom(kalimat):
  bersih = kalimat.replace("" ,"").lower()
  return bersih == bersih[::-1]

kata = input("Masukkan Kalimat : ")
print(cek_palindrom(kata))

#7
def panjang_kata(kalimat):
  kata_list = kalimat.split()
  panjang_kata = [len(kata) for kata in kata_list]
  return min(panjang_kata), max(panjang_kata)

kalimat = input("Masukkan Kalimat : ")
min_len, max_len = panjang_kata(kalimat)
print(panjang_kata(kalimat))

#8
def angka_romawi(n):
  if not (1 <= n <= 100):
    return "Angka tidak ada"

  angka_romawi = [
      (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
      (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I")
      ]

  hasil = ""
  for nilai, simbol in angka_romawi:
    while n >= nilai:
      hasil += simbol
      n -= nilai
  return hasil

n = int(input("Masukkan angka (1-100): "))
print(angka_romawi(n))